spring:
  application:
    name: spring-hazelcast
  jpa:
    properties:
      hibernate:
        show_sql: true
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory